### ISSUE TITLE
BCPM_Implementation final cell breaks

### ISSUE THREAD

**Issue by atcemgil** [pilab-sigma/bcpm#1]
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-8-22be374d4de2> in <module>()
     49 
     50 # Comment in for running C++ vs Python Test
---> 51 test_cpp_python()

<ipython-input-8-22be374d4de2> in test_cpp_python()
     37 
     38     cpp_result_f = Result.load(work_dir+"/filtering_cpp")
---> 39     np.testing.assert_array_almost_equal(cpp_result_f.cpp, result_f.cpp, decimal=5)
     40     np.testing.assert_array_almost_equal(cpp_result_f.ll, result_f.ll, decimal=5)
     41 

/Users/cemgil/anaconda/envs/py35/lib/python3.5/site-packages/numpy/testing/utils.py in assert_array_almost_equal(x, y, decimal, err_msg, verbose)
    914     assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,
    915              header=('Arrays are not almost equal to %d decimals' % decimal),
--> 916              precision=decimal)
    917 
    918 

/Users/cemgil/anaconda/envs/py35/lib/python3.5/site-packages/numpy/testing/utils.py in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision)
    690                                 names=('x', 'y'), precision=precision)
    691             if not cond:
--> 692                 raise AssertionError(msg)
    693 
    694         if isnumber(x) and isnumber(y):

AssertionError: 
Arrays are not almost equal to 5 decimals

(shapes (0,), (30,) mismatch)
 x: array([], dtype=float64)
 y: array([  5.00000e-02,   9.18656e-04,   5.55135e-03,   9.48341e-03,
         1.31939e-04,   2.28074e-04,   5.86565e-03,   2.38647e-04,
         3.82283e-04,   2.46335e-04,   3.18085e-04,   1.00265e-03,...

**Comment by bariskurt** [comment]
It was due to a bad path name. Fixed.
