### ISSUE TITLE
Bayesian_Change_Point_Model: Cell Well-Log Data (execution via C++)¶

### ISSUE THREAD

**Issue by atcemgil** [pilab-sigma/bcpm#2]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-8c637c80d03f> in <module>()
     47 # load and visualize results
     48 cpp_result = Result.load(work_dir+"/online_smoothing_cpp")
---> 49 plot_well_log(well_log_data, cpps=cpp_result.cpp, mean=cpp_result.mean.squeeze())

AttributeError: 'list' object has no attribute 'squeeze'

**Comment by bariskurt** [comment]
Another a bad path name. Now all notebooks should run fine.
